import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, LinearProgress, MenuItem, Select, TextField } from '@mui/material';
import type { Locale } from './lib/preferences';
import { availabilityApi, type AvailabilityApi, type AvailabilityReasonCode } from './lib/availabilityApi';
import { Stack, Typography } from './ui/MuiCompat';
const labels:Record<Locale,Record<AvailabilityReasonCode,string>>={'pt-PT':{away:'Ausente',unavailable:'Indisponível',other:'Outro'},en:{away:'Away',unavailable:'Unavailable',other:'Other'},es:{away:'Ausente',unavailable:'No disponible',other:'Otro'}};
const copy={'pt-PT':{title:'Períodos de ausência',add:'Adicionar ausência',start:'Início',end:'Fim',reason:'Motivo',remove:'Remover',empty:'Nenhum período de ausência.',error:'Não foi possível carregar os períodos.',range:'O fim deve ser posterior ao início.',retry:'Tentar novamente',save:'Guardar',cancel:'Cancelar'},en:{title:'Away periods',add:'Add absence',start:'Start',end:'End',reason:'Reason',remove:'Remove',empty:'No away periods.',error:'Away periods could not be loaded.',range:'End must be after start.',retry:'Try again',save:'Save',cancel:'Cancel'},es:{title:'Períodos de ausencia',add:'Agregar ausencia',start:'Inicio',end:'Fin',reason:'Motivo',remove:'Eliminar',empty:'No hay períodos de ausencia.',error:'No se pudieron cargar los períodos.',range:'El fin debe ser posterior al inicio.',retry:'Intentar de nuevo',save:'Guardar',cancel:'Cancelar'}} as const;
function date(value:string,locale:Locale):string{const ms=Date.parse(value);return Number.isFinite(ms)?new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(ms)):value;}
export function AwayPeriodsSection({locale,personId,api=availabilityApi}:{locale:Locale;personId:string;api?:AvailabilityApi}){const t=copy[locale];const[periods,setPeriods]=useState<Awaited<ReturnType<AvailabilityApi['list']>>>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[start,setStart]=useState('');const[end,setEnd]=useState('');const[reason,setReason]=useState<AvailabilityReasonCode|''>('');
const load=async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{setPeriods(await api.list(personId,signal));}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(t.error);}finally{if(!signal?.aborted)setLoading(false);}};useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[api,personId]);const sorted=useMemo(()=>[...periods].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)),[periods]);
const add=async(e:FormEvent)=>{e.preventDefault();if(!start||!end)return;if(Date.parse(end)<=Date.parse(start)){setError(t.range);return;}setSaving(true);setError(null);try{const created=await api.add(personId,{startsAt:start,endsAt:end,...(reason?{reasonCode:reason}:{})});setPeriods(cur=>[...cur,created]);setOpen(false);setStart('');setEnd('');setReason('');}catch{setError(t.error);}finally{setSaving(false);}};
const remove=async(id:string)=>{try{await api.remove(personId,id);setPeriods(cur=>cur.filter(x=>x.id!==id));}catch{setError(t.error);}};
return <Box component="section" aria-labelledby="away-periods-title"><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1} sx={{mb:2}}><Typography variant="h6" id="away-periods-title" fontWeight={700}>{t.title}</Typography><Button variant="outlined" onClick={()=>setOpen(true)}>{t.add}</Button></Stack>{error?<Alert severity="warning" action={<Button color="inherit" size="small" onClick={()=>void load()}>{t.retry}</Button>} sx={{mb:2}}>{error}</Alert>:null}{loading?<LinearProgress aria-label={t.title}/>:null}{!loading&&!error&&sorted.length===0?<Typography color="text.secondary" sx={{py:3,textAlign:'center'}}>{t.empty}</Typography>:null}{!loading&&sorted.length>0?<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))'},gap:2}}>{sorted.map(p=><Card key={p.id}><CardContent><Stack spacing={1}><Typography fontWeight={600}>{date(p.startsAt,locale)} — {date(p.endsAt,locale)}</Typography>{p.reasonCode?<Chip label={labels[locale][p.reasonCode]} size="small" sx={{alignSelf:'flex-start'}}/>:null}<Button size="small" color="error" sx={{alignSelf:'flex-start'}} onClick={()=>void remove(p.id)}>{t.remove}</Button></Stack></CardContent></Card>)}</Box>:null}<Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={add}><DialogTitle>{t.add}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label={t.start} type="date" value={start} onChange={e=>setStart(e.target.value)} required slotProps={{inputLabel:{shrink:true}}}/><TextField label={t.end} type="date" value={end} onChange={e=>setEnd(e.target.value)} required slotProps={{inputLabel:{shrink:true},htmlInput:{min:start||undefined}}}/><FormControl><InputLabel>{t.reason}</InputLabel><Select value={reason} label={t.reason} onChange={e=>setReason(e.target.value as AvailabilityReasonCode|'')}><MenuItem value=""><em>—</em></MenuItem>{(['away','unavailable','other'] as const).map(r=><MenuItem key={r} value={r}>{labels[locale][r]}</MenuItem>)}</Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>{t.cancel}</Button><Button type="submit" variant="contained" disabled={saving||!start||!end}>{t.save}</Button></DialogActions></Box></Dialog></Box>;}
