import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Paper, TextField } from '@mui/material';
import type { Locale } from './lib/preferences';
import { householdsApi, type HouseholdDto, type HouseholdsApi } from './lib/householdsApi';
import { Stack, Typography } from './ui/MuiCompat';

const copy={
'pt-PT':{title:'Agregados familiares',create:'Criar agregado',name:'Nome',members:'IDs dos membros',edit:'Editar',del:'Eliminar',save:'Guardar',cancel:'Cancelar',confirm:'Eliminar agregado?',empty:'Nenhum agregado familiar.',error:'Não foi possível carregar os agregados.',retry:'Tentar novamente',hint:'IDs separados por vírgula'},
en:{title:'Households',create:'Create household',name:'Name',members:'Member IDs',edit:'Edit',del:'Delete',save:'Save',cancel:'Cancel',confirm:'Delete household?',empty:'No households.',error:'Households could not be loaded.',retry:'Try again',hint:'Comma-separated IDs'},
es:{title:'Grupos familiares',create:'Crear grupo',name:'Nombre',members:'IDs de miembros',edit:'Editar',del:'Eliminar',save:'Guardar',cancel:'Cancelar',confirm:'¿Eliminar grupo familiar?',empty:'No hay grupos familiares.',error:'No se pudieron cargar los grupos.',retry:'Intentar de nuevo',hint:'IDs separados por coma'},
} as const;

export function HouseholdsSection({locale,api=householdsApi}:{locale:Locale;api?:HouseholdsApi}){
 const t=copy[locale]; const[items,setItems]=useState<readonly HouseholdDto[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<HouseholdDto|null>(null);const[deleteId,setDeleteId]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[name,setName]=useState('');const[members,setMembers]=useState('');
 const load=async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{setItems(await api.list(signal));}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(t.error);}finally{if(!signal?.aborted)setLoading(false);}};
 useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[api]);
 const begin=(item?:HouseholdDto)=>{setEditing(item??null);setName(item?.name??'');setMembers(item?.memberIds.join(', ')??'');setOpen(true);};
 const submit=async(e:FormEvent)=>{e.preventDefault();const n=name.trim();if(!n)return;const memberIds=[...new Set(members.split(',').map(x=>x.trim()).filter(Boolean))];setSaving(true);setError(null);try{const saved=editing?await api.update(editing.id,{name:n,memberIds}):await api.create({name:n,memberIds});setItems(cur=>editing?cur.map(x=>x.id===saved.id?saved:x):[...cur,saved]);setOpen(false);}catch{setError(t.error);}finally{setSaving(false);}};
 const remove=async()=>{if(!deleteId)return;try{await api.delete(deleteId);setItems(cur=>cur.filter(x=>x.id!==deleteId));setDeleteId(null);}catch{setError(t.error);setDeleteId(null);}};
 return <Box component="section" aria-labelledby="households-title"><Paper sx={{p:{xs:2,sm:3},mb:2}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Typography variant="h2" id="households-title" sx={{fontSize:{xs:'2rem',sm:'2.6rem'}}}>{t.title}</Typography><Button variant="contained" onClick={()=>begin()}>{t.create}</Button></Stack></Paper>{loading?<LinearProgress aria-label={t.title}/>:null}{error?<Alert severity="warning" action={<Button color="inherit" size="small" onClick={()=>void load()}>{t.retry}</Button>}>{error}</Alert>:null}{!loading&&!error&&items.length===0?<Paper sx={{p:4,textAlign:'center'}}><Typography color="text.secondary">{t.empty}</Typography></Paper>:null}{!loading&&items.length>0?<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))',xl:'repeat(3,minmax(0,1fr))'},gap:2,mt:2}}>{items.map(item=><Card component="article" key={item.id}><CardContent><Stack spacing={1.5}><Typography variant="h6" fontWeight={700}>{item.name}</Typography><Typography color="text.secondary">{item.memberIds.length} {locale==='en'?'members':locale==='es'?'miembros':'membros'}</Typography><Stack direction="row" gap={1}><Button size="small" onClick={()=>begin(item)}>{t.edit}</Button><Button size="small" color="error" onClick={()=>setDeleteId(item.id)}>{t.del}</Button></Stack></Stack></CardContent></Card>)}</Box>:null}<Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit}><DialogTitle>{editing?t.edit:t.create}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label={t.name} value={name} onChange={e=>setName(e.target.value)} required autoFocus slotProps={{htmlInput:{maxLength:120}}}/><TextField label={t.members} value={members} onChange={e=>setMembers(e.target.value)} helperText={t.hint} multiline minRows={2}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={saving}>{t.cancel}</Button><Button type="submit" variant="contained" disabled={saving||!name.trim()}>{t.save}</Button></DialogActions></Box></Dialog><Dialog open={deleteId!==null} onClose={()=>setDeleteId(null)}><DialogTitle>{t.confirm}</DialogTitle><DialogActions><Button onClick={()=>setDeleteId(null)}>{t.cancel}</Button><Button color="error" variant="contained" onClick={()=>void remove()}>{t.del}</Button></DialogActions></Dialog></Box>;
}
