import { useState, type FormEvent } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, TextField } from '@mui/material';
import { midweekApi, type MidweekMeetingDto, type NonStudentAssignmentDto, type StudentAssignmentDto } from './lib/midweekApi';
import type { PersonProfileDto } from './lib/peopleApi';
import type { Locale } from './lib/preferences';
import {
  BUILTIN_PARTS,
  builtinPart,
  CUSTOM_ASSIGNMENT_TYPE_CHOICE,
  resolveAssignmentTypeChoice,
  slotAllowsStudentAssignment,
  STANDARD_NON_STUDENT_ROLES,
} from './lib/assignmentTypeCatalog';
import { Stack, Typography } from './ui/MuiCompat';

export { BUILTIN_PARTS, slotAllowsStudentAssignment };

const copy = {
  'pt-PT': { createMeeting:'Nova reunião', meetingTitle:'Criar reunião', date:'Data', time:'Hora', timezone:'Fuso horário', location:'Local (opcional)', addPart:'Adicionar parte', partTitle:'Nova parte', titleKey:'Título / chave da parte', duration:'Duração (min)', partDefinition:'Tipo de parte', customPart:'Parte personalizada / função', assignStudent:'Designar estudante', assignRole:'Designar função', student:'Estudante', assistant:'Ajudante (opcional)', assistantRequired:'Ajudante (obrigatório)', person:'Pessoa', role:'Função', chooseRole:'Seleciona uma função', customRole:'Outra função personalizada…', customRoleId:'Identificador da função personalizada', none:'Sem ajudante', publish:'Publicar', removePart:'Remover parte', replace:'Substituir', cancelAssignment:'Cancelar designação', save:'Guardar', cancel:'Cancelar', working:'A guardar…', error:'Não foi possível concluir a operação.', publishConfirm:'Publicar esta reunião? Depois de publicada, as alterações ficam mais restritas.', confirm:'Confirmar', noPeople:'Não existem pessoas ativas disponíveis.' },
  en: { createMeeting:'New meeting', meetingTitle:'Create meeting', date:'Date', time:'Time', timezone:'Timezone', location:'Location (optional)', addPart:'Add part', partTitle:'New part', titleKey:'Part title / key', duration:'Duration (min)', partDefinition:'Part type', customPart:'Custom part / role', assignStudent:'Assign student', assignRole:'Assign role', student:'Student', assistant:'Assistant (optional)', assistantRequired:'Assistant (required)', person:'Person', role:'Role', chooseRole:'Select a role', customRole:'Another custom role…', customRoleId:'Custom role identifier', none:'No assistant', publish:'Publish', removePart:'Remove part', replace:'Replace', cancelAssignment:'Cancel assignment', save:'Save', cancel:'Cancel', working:'Saving…', error:'The operation could not be completed.', publishConfirm:'Publish this meeting? Changes become more restricted after publishing.', confirm:'Confirm', noPeople:'No active people are available.' },
  es: { createMeeting:'Nueva reunión', meetingTitle:'Crear reunión', date:'Fecha', time:'Hora', timezone:'Zona horaria', location:'Lugar (opcional)', addPart:'Añadir parte', partTitle:'Nueva parte', titleKey:'Título / clave de la parte', duration:'Duración (min)', partDefinition:'Tipo de parte', customPart:'Parte personalizada / función', assignStudent:'Asignar estudiante', assignRole:'Asignar función', student:'Estudiante', assistant:'Ayudante (opcional)', assistantRequired:'Ayudante (obligatorio)', person:'Persona', role:'Función', chooseRole:'Selecciona una función', customRole:'Otra función personalizada…', customRoleId:'Identificador de la función personalizada', none:'Sin ayudante', publish:'Publicar', removePart:'Eliminar parte', replace:'Sustituir', cancelAssignment:'Cancelar asignación', save:'Guardar', cancel:'Cancelar', working:'Guardando…', error:'No se pudo completar la operación.', publishConfirm:'¿Publicar esta reunión? Después de publicarla, los cambios estarán más restringidos.', confirm:'Confirmar', noPeople:'No hay personas activas disponibles.' },
} as const;

function localTimezone(): string {
  try { return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'; }
  catch { return 'UTC'; }
}

export function CreateMidweekMeetingControl({ locale, onChanged }: { locale:Locale; onChanged:()=>Promise<void>|void }) {
  const text=copy[locale]; const [open,setOpen]=useState(false); const [date,setDate]=useState(''); const [time,setTime]=useState('19:30'); const [timezone,setTimezone]=useState(localTimezone); const [location,setLocation]=useState(''); const [working,setWorking]=useState(false); const [error,setError]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!date||!time||!timezone.trim()||working)return;setWorking(true);setError(false);try{await midweekApi.createMeeting({date,localTime:time,timezone:timezone.trim(),...(location.trim()?{locationId:location.trim()}:{})});setOpen(false);setDate('');setLocation('');await onChanged();}catch{setError(true);}finally{setWorking(false);}};
  return <><Button variant="contained" onClick={()=>{setError(false);setOpen(true);}}>{text.createMeeting}</Button><Dialog open={open} onClose={()=>!working&&setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>{text.meetingTitle}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField type="date" label={text.date} value={date} onChange={e=>setDate(e.target.value)} required slotProps={{inputLabel:{shrink:true}}}/><TextField type="time" label={text.time} value={time} onChange={e=>setTime(e.target.value)} required slotProps={{inputLabel:{shrink:true},htmlInput:{step:60}}}/><TextField label={text.timezone} value={timezone} onChange={e=>setTimezone(e.target.value)} required/><TextField label={text.location} value={location} onChange={e=>setLocation(e.target.value)} slotProps={{htmlInput:{maxLength:200}}}/>{error?<Alert severity="error">{text.error}</Alert>:null}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={working}>{text.cancel}</Button><Button type="submit" variant="contained" disabled={working||!date||!time||!timezone.trim()}>{working?text.working:text.save}</Button></DialogActions></form></Dialog></>;
}

type AssignmentKind='student'|'role';
export function MidweekMeetingControls({ locale, meeting, people, onChanged }:{ locale:Locale; meeting:MidweekMeetingDto; people:readonly PersonProfileDto[]; onChanged:()=>Promise<void>|void }) {
  const text=copy[locale]; const activePeople=people.filter(person=>person.active); const [partOpen,setPartOpen]=useState(false); const [titleKey,setTitleKey]=useState(''); const [duration,setDuration]=useState('5'); const [definition,setDefinition]=useState(''); const [assignment,setAssignment]=useState<{kind:AssignmentKind;slotId:string}|null>(null); const [personId,setPersonId]=useState(''); const [assistantId,setAssistantId]=useState(''); const [roleChoice,setRoleChoice]=useState(''); const [customRole,setCustomRole]=useState(''); const [working,setWorking]=useState(false); const [error,setError]=useState(false); const [publishOpen,setPublishOpen]=useState(false);
  if(meeting.state!=='draft')return meeting.slots.length?<Stack spacing={.75}>{meeting.slots.map(slot=><Typography key={slot.id} variant="body2">{slot.position+1}. {slot.titleKey} · {slot.durationMinutes} min</Typography>)}</Stack>:null;
  const run=async(op:()=>Promise<unknown>)=>{if(working)return;setWorking(true);setError(false);try{await op();await onChanged();return true;}catch{setError(true);return false;}finally{setWorking(false);}};
  const addPart=async(event:FormEvent)=>{event.preventDefault();if(!titleKey.trim()||!Number.isInteger(Number(duration))||Number(duration)<=0)return;const ok=await run(()=>midweekApi.addSlot(meeting.id,{position:meeting.slots.length,durationMinutes:Number(duration),titleKey:titleKey.trim(),...(definition?{partDefinitionId:definition}:{})}));if(ok){setPartOpen(false);setTitleKey('');setDuration('5');setDefinition('');}};
  const selectedAssignmentPart=assignment?builtinPart(meeting.slots.find(slot=>slot.id===assignment.slotId)?.partDefinitionId):undefined;
  const requiresAssistant=assignment?.kind==='student'&&selectedAssignmentPart?.assistantRequirement==='required';
  const resolvedRole=resolveAssignmentTypeChoice(roleChoice,customRole);
  const saveAssignment=async(event:FormEvent)=>{event.preventDefault();if(!assignment||!personId||(requiresAssistant&&!assistantId))return;const ok=assignment.kind==='student'?await run(()=>midweekApi.assignStudent(meeting.id,{slotId:assignment.slotId,studentId:personId,assistantId:assistantId||null})):resolvedRole?await run(()=>midweekApi.assignNonStudent(meeting.id,{slotId:assignment.slotId,personId,role:resolvedRole})):false;if(ok){setAssignment(null);setPersonId('');setAssistantId('');setRoleChoice('');setCustomRole('');}};
  const chooseDefinition=(partId:string)=>{setDefinition(partId);const part=builtinPart(partId);if(part){setTitleKey(part.titleKey);setDuration(String(part.durationMinutes));}};
  return <Stack spacing={1.25}><Divider/>{meeting.slots.map(slot=><Stack key={slot.id} direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}} justifyContent="space-between"><Typography variant="body2"><strong>{slot.position+1}. {slot.titleKey}</strong> · {slot.durationMinutes} min</Typography><Stack direction="row" spacing={.5} flexWrap="wrap" useFlexGap>{slotAllowsStudentAssignment(slot.partDefinitionId)?<Button size="small" disabled={working||!activePeople.length} onClick={()=>{setError(false);setAssignment({kind:'student',slotId:slot.id});}}>{text.assignStudent}</Button>:null}<Button size="small" disabled={working||!activePeople.length} onClick={()=>{setError(false);setAssignment({kind:'role',slotId:slot.id});}}>{text.assignRole}</Button><Button size="small" color="warning" disabled={working} onClick={()=>void run(()=>midweekApi.removeSlot(meeting.id,slot.id))}>{text.removePart}</Button></Stack></Stack>)}{!activePeople.length?<Typography variant="caption" color="text.secondary">{text.noPeople}</Typography>:null}{error?<Alert severity="error">{text.error}</Alert>:null}<Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap><Button variant="outlined" disabled={working} onClick={()=>{setError(false);setPartOpen(true);}}>{text.addPart}</Button><Button variant="contained" disabled={working} onClick={()=>{setError(false);setPublishOpen(true);}}>{text.publish}</Button></Stack>
  <Dialog open={partOpen} onClose={()=>!working&&setPartOpen(false)} fullWidth maxWidth="sm"><form onSubmit={addPart}><DialogTitle>{text.partTitle}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField select label={text.partDefinition} value={definition} onChange={e=>chooseDefinition(e.target.value)}><MenuItem value="">{text.customPart}</MenuItem>{BUILTIN_PARTS.map(part=><MenuItem key={part.id} value={part.id}>{part.label[locale]}</MenuItem>)}</TextField><TextField label={text.titleKey} value={titleKey} onChange={e=>setTitleKey(e.target.value)} required/><TextField type="number" label={text.duration} value={duration} onChange={e=>setDuration(e.target.value)} required slotProps={{htmlInput:{min:1,max:180,step:1}}}/>{error?<Alert severity="error">{text.error}</Alert>:null}</Stack></DialogContent><DialogActions><Button onClick={()=>setPartOpen(false)} disabled={working}>{text.cancel}</Button><Button type="submit" variant="contained" disabled={working||!titleKey.trim()}>{working?text.working:text.save}</Button></DialogActions></form></Dialog>
  <Dialog open={assignment!==null} onClose={()=>!working&&setAssignment(null)} fullWidth maxWidth="sm"><form onSubmit={saveAssignment}><DialogTitle>{assignment?.kind==='student'?text.assignStudent:text.assignRole}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField select label={assignment?.kind==='student'?text.student:text.person} value={personId} onChange={e=>setPersonId(e.target.value)} required>{activePeople.map(person=><MenuItem key={person.id} value={person.id}>{person.displayName}</MenuItem>)}</TextField>{assignment?.kind==='student'?<TextField select label={requiresAssistant?text.assistantRequired:text.assistant} value={assistantId} onChange={e=>setAssistantId(e.target.value)} required={requiresAssistant}><MenuItem value="">{text.none}</MenuItem>{activePeople.filter(p=>p.id!==personId).map(person=><MenuItem key={person.id} value={person.id}>{person.displayName}</MenuItem>)}</TextField>:<><TextField select label={text.role} value={roleChoice} onChange={e=>{setRoleChoice(e.target.value);setCustomRole('');}} required><MenuItem value="" disabled>{text.chooseRole}</MenuItem>{STANDARD_NON_STUDENT_ROLES.map(option=><MenuItem key={option.id} value={option.id}>{option.label[locale]}</MenuItem>)}<MenuItem value={CUSTOM_ASSIGNMENT_TYPE_CHOICE}>{text.customRole}</MenuItem></TextField>{roleChoice===CUSTOM_ASSIGNMENT_TYPE_CHOICE?<TextField label={text.customRoleId} value={customRole} onChange={e=>setCustomRole(e.target.value)} required slotProps={{htmlInput:{maxLength:100,autoComplete:'off'}}}/>:null}</>}{error?<Alert severity="error">{text.error}</Alert>:null}</Stack></DialogContent><DialogActions><Button onClick={()=>setAssignment(null)} disabled={working}>{text.cancel}</Button><Button type="submit" variant="contained" disabled={working||!personId||(assignment?.kind==='role'&&!resolvedRole)||Boolean(requiresAssistant&&!assistantId)}>{working?text.working:text.save}</Button></DialogActions></form></Dialog>
  <Dialog open={publishOpen} onClose={()=>!working&&setPublishOpen(false)}><DialogTitle>{text.publish}</DialogTitle><DialogContent><Typography>{text.publishConfirm}</Typography>{error?<Alert severity="error" sx={{mt:2}}>{text.error}</Alert>:null}</DialogContent><DialogActions><Button onClick={()=>setPublishOpen(false)} disabled={working}>{text.cancel}</Button><Button variant="contained" disabled={working} onClick={async()=>{const ok=await run(()=>midweekApi.publishMeeting(meeting.id));if(ok)setPublishOpen(false);}}>{working?text.working:text.confirm}</Button></DialogActions></Dialog>
  </Stack>;
}

export function StudentAssignmentControls({ locale, assignment, people, onChanged }:{locale:Locale;assignment:StudentAssignmentDto;people:readonly PersonProfileDto[];onChanged:()=>Promise<void>|void}){
  const text=copy[locale];const [open,setOpen]=useState(false);const [studentId,setStudentId]=useState(assignment.studentId);const [assistantId,setAssistantId]=useState(assignment.assistantId??'');const [working,setWorking]=useState(false);const [error,setError]=useState(false);const active=people.filter(p=>p.active);if(assignment.state!=='assigned')return null;
  const run=async(op:()=>Promise<void>)=>{setWorking(true);setError(false);try{await op();await onChanged();return true;}catch{setError(true);return false;}finally{setWorking(false);}};
  return <><Stack direction="row" spacing={1}><Button size="small" variant="outlined" onClick={()=>setOpen(true)}>{text.replace}</Button><Button size="small" color="warning" disabled={working} onClick={()=>void run(()=>midweekApi.cancelStudent(assignment.id))}>{text.cancelAssignment}</Button></Stack><Dialog open={open} onClose={()=>!working&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{text.replace}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField select label={text.student} value={studentId} onChange={e=>setStudentId(e.target.value)}>{active.map(p=><MenuItem key={p.id} value={p.id}>{p.displayName}</MenuItem>)}</TextField><TextField select label={text.assistant} value={assistantId} onChange={e=>setAssistantId(e.target.value)}><MenuItem value="">{text.none}</MenuItem>{active.filter(p=>p.id!==studentId).map(p=><MenuItem key={p.id} value={p.id}>{p.displayName}</MenuItem>)}</TextField>{error?<Alert severity="error">{text.error}</Alert>:null}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={working}>{text.cancel}</Button><Button variant="contained" disabled={working||!studentId} onClick={async()=>{const ok=await run(()=>midweekApi.replaceStudent(assignment.id,{studentId,assistantId:assistantId||null}));if(ok)setOpen(false);}}>{working?text.working:text.save}</Button></DialogActions></Dialog></>;
}

export function NonStudentAssignmentControls({ locale, assignment, people, onChanged }:{locale:Locale;assignment:NonStudentAssignmentDto;people:readonly PersonProfileDto[];onChanged:()=>Promise<void>|void}){
  const text=copy[locale];const [open,setOpen]=useState(false);const [personId,setPersonId]=useState(assignment.personId);const [working,setWorking]=useState(false);const [error,setError]=useState(false);const active=people.filter(p=>p.active);if(assignment.state!=='assigned')return null;
  const run=async(op:()=>Promise<void>)=>{setWorking(true);setError(false);try{await op();await onChanged();return true;}catch{setError(true);return false;}finally{setWorking(false);}};
  return <><Stack direction="row" spacing={1}><Button size="small" variant="outlined" onClick={()=>setOpen(true)}>{text.replace}</Button><Button size="small" color="warning" disabled={working} onClick={()=>void run(()=>midweekApi.cancelNonStudent(assignment.id))}>{text.cancelAssignment}</Button></Stack><Dialog open={open} onClose={()=>!working&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{text.replace}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField select label={text.person} value={personId} onChange={e=>setPersonId(e.target.value)}>{active.map(p=><MenuItem key={p.id} value={p.id}>{p.displayName}</MenuItem>)}</TextField>{error?<Alert severity="error">{text.error}</Alert>:null}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={working}>{text.cancel}</Button><Button variant="contained" disabled={working||!personId} onClick={async()=>{const ok=await run(()=>midweekApi.replaceNonStudent(assignment.id,personId));if(ok)setOpen(false);}}>{working?text.working:text.save}</Button></DialogActions></Dialog></>;
}
