import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Paper, TextField } from '@mui/material';
import type { Locale } from './lib/preferences';
import { responsibilitiesApi, type ResponsibilityDto, type ResponsibilitiesApi } from './lib/responsibilitiesApi';
import { Stack, Typography } from './ui/MuiCompat';
const copy={
'pt-PT':{title:'Responsabilidades',create:'Atribuir responsabilidade',person:'ID da pessoa',key:'Chave da responsabilidade',start:'Início',end:'Fim opcional',finish:'Terminar',save:'Guardar',cancel:'Cancelar',empty:'Nenhuma responsabilidade atribuída.',error:'Não foi possível carregar as responsabilidades.',retry:'Tentar novamente',active:'Ativa',ended:'Terminada',scheduledEnd:'Termina em',hint:'Ex.: som, literatura, tarefa-local'},
en:{title:'Responsibilities',create:'Assign responsibility',person:'Person ID',key:'Responsibility key',start:'Start',end:'Optional end',finish:'End',save:'Save',cancel:'Cancel',empty:'No responsibilities assigned.',error:'Responsibilities could not be loaded.',retry:'Try again',active:'Active',ended:'Ended',scheduledEnd:'Ends on',hint:'E.g. sound, literature, local-duty'},
es:{title:'Responsabilidades',create:'Asignar responsabilidad',person:'ID de persona',key:'Clave de responsabilidad',start:'Inicio',end:'Fin opcional',finish:'Terminar',save:'Guardar',cancel:'Cancelar',empty:'No hay responsabilidades asignadas.',error:'No se pudieron cargar las responsabilidades.',retry:'Intentar de nuevo',active:'Activa',ended:'Terminada',scheduledEnd:'Termina el',hint:'Ej.: sonido, literatura, tarea-local'},
} as const;
function localDate(d=new Date()):string{const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`;}
function displayDate(value:string,locale:Locale):string{const ms=Date.parse(value);if(!Number.isFinite(ms))return value;return new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(ms));}
export function ResponsibilitiesSection({locale,api=responsibilitiesApi}:{locale:Locale;api?:ResponsibilitiesApi}){const t=copy[locale];const[items,setItems]=useState<readonly ResponsibilityDto[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[personId,setPersonId]=useState('');const[key,setKey]=useState('');const[start,setStart]=useState(localDate());const[end,setEnd]=useState('');
const load=async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{setItems(await api.list(signal));}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(t.error);}finally{if(!signal?.aborted)setLoading(false);}};useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>c.abort();},[api]);
const submit=async(e:FormEvent)=>{e.preventDefault();if(!personId.trim()||!key.trim()||!start)return;if(end&&Date.parse(end)<=Date.parse(start)){setError(locale==='pt-PT'?'O fim deve ser posterior ao início.':locale==='es'?'El fin debe ser posterior al inicio.':'End must be after start.');return;}setSaving(true);setError(null);try{const created=await api.assign({personId:personId.trim(),responsibilityKey:key.trim(),startsAt:start,...(end?{endsAt:end}:{})});setItems(cur=>[...cur,created].sort((a,b)=>b.startsAt.localeCompare(a.startsAt)));setOpen(false);setPersonId('');setKey('');setStart(localDate());setEnd('');}catch{setError(t.error);}finally{setSaving(false);}};
const finish=async(item:ResponsibilityDto)=>{try{const updated=await api.end(item.id,{endsAt:localDate()});setItems(cur=>cur.map(x=>x.id===updated.id?updated:x));}catch{setError(t.error);}};
const now=Date.now();return <Box component="section" aria-labelledby="responsibilities-title"><Paper sx={{p:{xs:2,sm:3},mb:2}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Typography variant="h2" id="responsibilities-title" sx={{fontSize:{xs:'2rem',sm:'2.6rem'}}}>{t.title}</Typography><Button variant="contained" onClick={()=>setOpen(true)}>{t.create}</Button></Stack></Paper>{loading?<LinearProgress aria-label={t.title}/>:null}{error?<Alert severity="warning" action={<Button color="inherit" size="small" onClick={()=>void load()}>{t.retry}</Button>}>{error}</Alert>:null}{!loading&&!error&&items.length===0?<Paper sx={{p:4,textAlign:'center'}}><Typography color="text.secondary">{t.empty}</Typography></Paper>:null}{!loading&&items.length>0?<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))',xl:'repeat(3,minmax(0,1fr))'},gap:2,mt:2}}>{items.map(item=>{const ended=Boolean(item.endsAt&&Date.parse(item.endsAt)<=now);return <Card component="article" key={item.id}><CardContent><Stack spacing={1}><Stack direction="row" justifyContent="space-between" gap={1}><Typography variant="h6" fontWeight={700}>{item.responsibilityKey}</Typography><Chip size="small" label={ended?t.ended:t.active} color={ended?'default':'success'} variant="outlined"/></Stack><Typography variant="body2" color="text.secondary">{t.person}: {item.personId}</Typography><Typography variant="body2" color="text.secondary">{displayDate(item.startsAt,locale)}</Typography>{item.endsAt?<Typography variant="body2" color="text.secondary">{ended?t.ended:t.scheduledEnd}: {displayDate(item.endsAt,locale)}</Typography>:null}{!ended?<Button size="small" sx={{alignSelf:'flex-start'}} onClick={()=>void finish(item)}>{t.finish}</Button>:null}</Stack></CardContent></Card>;})}</Box>:null}<Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit}><DialogTitle>{t.create}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label={t.person} value={personId} onChange={e=>setPersonId(e.target.value)} required autoFocus/><TextField label={t.key} value={key} onChange={e=>setKey(e.target.value)} required helperText={t.hint}/><TextField label={t.start} type="date" value={start} onChange={e=>setStart(e.target.value)} required slotProps={{inputLabel:{shrink:true}}}/><TextField label={t.end} type="date" value={end} onChange={e=>setEnd(e.target.value)} slotProps={{inputLabel:{shrink:true},htmlInput:{min:start}}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>{t.cancel}</Button><Button type="submit" variant="contained" disabled={saving||!personId.trim()||!key.trim()}>{t.save}</Button></DialogActions></Box></Dialog></Box>;}
