import { useState } from 'react';
import { Box, Button, Card, CardContent, Chip, Paper } from '@mui/material';
import { AccessManagementDialog } from './AccessManagementDialog';
import { AuditHistoryDialog } from './AuditHistoryDialog';
import { HouseholdsSection } from './HouseholdsSection';
import { PeopleDirectory } from './PeopleDirectory';
import { ResponsibilitiesSection } from './ResponsibilitiesSection';
import { ServiceGroupsSection } from './ServiceGroupsSection';
import type { Locale } from './lib/preferences';
import { getWorkspaceCopy, type WorkspaceSection } from './lib/sectionData';
import { Stack, Typography } from './ui/MuiCompat';

interface SectionWorkspaceProps { locale: Locale; section: WorkspaceSection }
type OrganizationView='people'|'households'|'groups'|'responsibilities';
const orgLabels={
'pt-PT':{people:'Pessoas',households:'Agregados',groups:'Grupos de serviço',responsibilities:'Responsabilidades',audit:'Histórico de auditoria',access:'Gerir acessos'},
en:{people:'People',households:'Households',groups:'Service groups',responsibilities:'Responsibilities',audit:'Audit history',access:'Manage access'},
es:{people:'Personas',households:'Grupos familiares',groups:'Grupos de servicio',responsibilities:'Responsabilidades',audit:'Historial de auditoría',access:'Gestionar accesos'},
} as const;
function PeopleWorkspace({locale}:{locale:Locale}){const[view,setView]=useState<OrganizationView>('people');const[auditOpen,setAuditOpen]=useState(false);const[accessOpen,setAccessOpen]=useState(false);const t=orgLabels[locale];const views:readonly OrganizationView[]=['people','households','groups','responsibilities'];return <Stack spacing={1.5}><Paper component="nav" aria-label={locale==='pt-PT'?'Áreas de pessoas e organização':locale==='es'?'Áreas de personas y organización':'People and organization areas'} sx={{p:1.5}}><Stack direction="row" gap={1} flexWrap="wrap" useFlexGap>{views.map(item=><Button key={item} variant={view===item?'contained':'text'} aria-pressed={view===item} onClick={()=>setView(item)}>{t[item]}</Button>)}</Stack></Paper><Box sx={{display:'flex',justifyContent:'flex-end',gap:1,flexWrap:'wrap'}}><Button variant="outlined" onClick={()=>setAuditOpen(true)}>{t.audit}</Button><Button variant="outlined" onClick={()=>setAccessOpen(true)}>{t.access}</Button></Box>{view==='people'?<PeopleDirectory locale={locale}/>:null}{view==='households'?<HouseholdsSection locale={locale}/>:null}{view==='groups'?<ServiceGroupsSection locale={locale}/>:null}{view==='responsibilities'?<ResponsibilitiesSection locale={locale}/>:null}<AuditHistoryDialog locale={locale} open={auditOpen} onClose={()=>setAuditOpen(false)}/><AccessManagementDialog locale={locale} open={accessOpen} onClose={()=>setAccessOpen(false)}/></Stack>}
export function SectionWorkspace({locale,section}:SectionWorkspaceProps){if(section==='people')return <PeopleWorkspace locale={locale}/>;const content=getWorkspaceCopy(locale,section);const detailsLabel=locale==='pt-PT'?'Ver detalhes':locale==='es'?'Ver detalles':'View details';return <Box component="section" aria-labelledby={`section-${section}-title`}><Paper sx={{p:{xs:2,sm:3},mb:2,borderRadius:{xs:3,md:4}}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} alignItems={{sm:'flex-start'}}><Box><Typography variant="overline" color="text.secondary" fontWeight={800}>{content.eyebrow}</Typography><Typography variant="h2" id={`section-${section}-title`} sx={{fontSize:{xs:'2rem',sm:'2.6rem'}}}>{content.title}</Typography><Typography color="text.secondary" sx={{mt:1,maxWidth:760}}>{content.subtitle}</Typography></Box><Chip label="Preview" variant="outlined" color="primary"/></Stack></Paper><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'repeat(2,minmax(0,1fr))'},gap:2}}>{content.cards.map((card,index)=><Card component="article" key={`${section}-${index}`}><CardContent><Stack spacing={2}><Stack direction="row" justifyContent="space-between" alignItems="flex-start" gap={2}><Box><Typography variant="overline" color="text.secondary">{card.meta}</Typography><Typography variant="h5" fontWeight={750}>{card.title}</Typography></Box>{card.status?<Chip label={card.status} size="small" variant="outlined"/>:null}</Stack><Typography color="text.secondary">{card.detail}</Typography><Button variant="text" disabled sx={{alignSelf:'flex-start'}}>{detailsLabel} →</Button></Stack></CardContent></Card>)}</Box></Box>}
