import { describe, expect, it } from 'vitest';
import { createHouseholdsApi, parseHouseholdList } from './householdsApi';
import { createServiceGroupsApi, parseServiceGroupList } from './serviceGroupsApi';
import { createResponsibilitiesApi, parseResponsibilityList } from './responsibilitiesApi';
function response(body:unknown,status=200):Response{return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});}
describe('reviewed organization API boundaries',()=>{
 it('rejects privacy-boundary widening from server responses',()=>{expect(()=>parseHouseholdList([{id:'h1',name:'H',memberIds:[],tenantId:'secret'}])).toThrow('Invalid Households API response');expect(()=>parseServiceGroupList([{id:'g1',name:'G',memberIds:[],tenantId:'secret'}])).toThrow('Invalid Service Groups API response');expect(()=>parseResponsibilityList([{id:'r1',personId:'p1',responsibilityKey:'custom-duty',startsAt:'2026-01-01',assignedBy:'hidden'}])).toThrow('Invalid Responsibilities API response');});
 it('minimizes household writes even for adversarial runtime objects',async()=>{let init:RequestInit|undefined;const fetcher:typeof fetch=async(_input,next)=>{init=next;return response({id:'h1',name:'H',memberIds:[]});};await createHouseholdsApi(fetcher).create({name:'H',memberIds:[],tenantId:'evil',actorId:'evil'} as never);expect(JSON.parse(String(init?.body))).toEqual({name:'H',memberIds:[]});});
 it('minimizes service-group writes even for adversarial runtime objects',async()=>{let init:RequestInit|undefined;const fetcher:typeof fetch=async(_input,next)=>{init=next;return response({id:'g1',name:'G',memberIds:[]});};await createServiceGroupsApi(fetcher).create({name:'G',memberIds:[],tenantId:'evil',capabilities:['tenant.manage']} as never);expect(JSON.parse(String(init?.body))).toEqual({name:'G',memberIds:[]});});
 it('minimizes responsibility writes even for adversarial runtime objects',async()=>{let init:RequestInit|undefined;const fetcher:typeof fetch=async(_input,next)=>{init=next;return response({id:'r1',personId:'p1',responsibilityKey:'custom-duty',startsAt:'2026-01-01T00:00:00.000Z'});};await createResponsibilitiesApi(fetcher).assign({personId:'p1',responsibilityKey:'custom-duty',startsAt:'2026-01-01',tenantId:'evil',assignedBy:'evil'} as never);expect(JSON.parse(String(init?.body))).toEqual({personId:'p1',responsibilityKey:'custom-duty',startsAt:'2026-01-01T00:00:00.000Z'});});
 it('never exposes server-provided 5xx details',async()=>{const fetcher:typeof fetch=async()=>response({error:'database password leaked'},500);await expect(createHouseholdsApi(fetcher).list()).rejects.toThrow('Households API request failed (500)');await expect(createServiceGroupsApi(fetcher).list()).rejects.toThrow('Service Groups API request failed (500)');await expect(createResponsibilitiesApi(fetcher).list()).rejects.toThrow('Responsibilities API request failed (500)');});
 it('uses same-origin credentials on reads',async()=>{let init:RequestInit|undefined;const fetcher:typeof fetch=async(_input,next)=>{init=next;return response([]);};await createHouseholdsApi(fetcher).list();expect(init?.credentials).toBe('same-origin');});
});