import { createMigrationSchema, MIGRATION_LIMITS, type MigrationSchema } from './migration-schema';

const REQUIRED_HEADERS=['externalId','displayName','active'] as const;
const OPTIONAL_HEADERS=['preferredLocale'] as const;
const ALLOWED_HEADERS=new Set<string>([...REQUIRED_HEADERS,...OPTIONAL_HEADERS]);
function formulaEncoded(value:string):string{if(value.startsWith("'")&&/^[=+\-@]/.test(value.slice(1)))return value.slice(1);return value;}
function unsafeFormula(value:string):boolean{return /^[\s\t\r\n]*[=+\-@]/.test(value)&&!(value.startsWith("'")&&/^[=+\-@]/.test(value.slice(1)));}
function parseCsv(text:string):string[][]{if(new TextEncoder().encode(text).length>MIGRATION_LIMITS.maxCsvBytes)throw new Error('CSV file is too large');const rows:string[][]=[];let row:string[]=[];let field='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++;}else{quoted=false;}}else{field+=ch;if(field.length>MIGRATION_LIMITS.maxField)throw new Error('CSV field is too large');}continue;}if(ch==='"'){if(field.length!==0)throw new Error('Malformed CSV quote');quoted=true;continue;}if(ch===','){row.push(field);field='';continue;}if(ch==='\r'||ch==='\n'){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(cell=>cell.length>0))rows.push(row);row=[];if(rows.length>MIGRATION_LIMITS.maxRows+1)throw new Error('CSV contains too many rows');continue;}field+=ch;if(field.length>MIGRATION_LIMITS.maxField)throw new Error('CSV field is too large');}if(quoted)throw new Error('Unterminated CSV quoted field');if(field.length||row.length){row.push(field);if(row.some(cell=>cell.length>0))rows.push(row);}return rows;}
export interface CsvImportResult{readonly schema:Readonly<MigrationSchema>;readonly warnings:readonly string[]}
export function importPeopleCsv(csv:string,exportedAt:string):CsvImportResult{const rows=parseCsv(csv.replace(/^\uFEFF/,''));if(rows.length===0)throw new Error('CSV is empty');const headers=rows[0].map(h=>h.trim());const seen=new Set<string>();for(const h of headers){if(!h)throw new Error('CSV header must not be empty');if(seen.has(h))throw new Error(`Duplicate CSV header: ${h}`);seen.add(h);if(!ALLOWED_HEADERS.has(h))throw new Error(`Unsupported CSV header: ${h}`);}for(const required of REQUIRED_HEADERS){if(!seen.has(required))throw new Error(`Missing required CSV header: ${required}`);}const warnings:string[]=[];const data=rows.slice(1).map((cells,index)=>{if(cells.length!==headers.length)return {externalId:'',displayName:'',active:'',sourceError:`row ${index+2} has ${cells.length} columns; expected ${headers.length}`};const obj:Record<string,unknown>={};for(let c=0;c<headers.length;c++){const raw=cells[c];if(unsafeFormula(raw)){obj[headers[c]]='';obj.sourceError=`row ${index+2} contains unsafe spreadsheet formula input`;warnings.push(`Row ${index+2} rejected unsafe spreadsheet formula input`);continue;}obj[headers[c]]=formulaEncoded(raw);}return obj;});const schema=createMigrationSchema(data.map((row,index)=>{const sourceError=(row as Record<string,unknown>).sourceError;if(typeof sourceError==='string')return {externalId:'',displayName:'',active:'',preferredLocale:'',__error:sourceError};return row;}),exportedAt);const patched=schema.rows.map((row,index)=>{const original=data[index] as Record<string,unknown>;const sourceError=original.sourceError;if(typeof sourceError!=='string')return row;const errors=Object.freeze([...row.errors,sourceError]);return Object.freeze({...row,errors,isValid:false});});return Object.freeze({schema:Object.freeze({...schema,rows:Object.freeze(patched)}),warnings:Object.freeze(warnings)});}
