export type MigrationStatus='running'|'completed'|'failed'|'rolled-back';
export type MigrationOperationKind='create'|'update';
export interface MigrationLogEntry{readonly sequence:number;readonly operationId:string;readonly kind:MigrationOperationKind;readonly internalId:string;readonly executedAt:string}
export interface MigrationLog{readonly tenantId:string;readonly migrationId:string;readonly startedAt:string;readonly completedAt?:string;readonly status:MigrationStatus;readonly operations:readonly MigrationLogEntry[]}
export interface RollbackPersonSnapshot{readonly externalId:string;readonly displayName:string;readonly active:boolean;readonly preferredLocale?:string}
export interface RollbackStep{readonly sequence:number;readonly type:'delete'|'restore';readonly internalId:string;readonly restore?:Readonly<RollbackPersonSnapshot>}
export interface RollbackPlan{readonly tenantId:string;readonly migrationId:string;readonly steps:readonly RollbackStep[]}
function required(v:string,label:string):string{const n=v.trim();if(!n)throw new Error(`${label} is required`);if(n.length>200)throw new Error(`${label} is too long`);return n;}
function instant(v:string,label:string):string{if(!Number.isFinite(Date.parse(v)))throw new Error(`${label} must be an ISO date`);return v;}
function cloneSnapshot(v:RollbackPersonSnapshot):Readonly<RollbackPersonSnapshot>{return Object.freeze({externalId:required(v.externalId,'externalId'),displayName:required(v.displayName,'displayName'),active:v.active,...(v.preferredLocale?{preferredLocale:v.preferredLocale}:{})});}
export function createMigrationLog(input:{tenantId:string;migrationId:string;startedAt:string}):Readonly<MigrationLog>{return Object.freeze({tenantId:required(input.tenantId,'tenantId'),migrationId:required(input.migrationId,'migrationId'),startedAt:instant(input.startedAt,'startedAt'),status:'running',operations:Object.freeze([])});}
export function appendMigrationOperation(log:Readonly<MigrationLog>,input:{operationId:string;kind:MigrationOperationKind;internalId:string;executedAt:string}):Readonly<MigrationLog>{if(log.status!=='running')throw new Error('Migration is not running');const operationId=required(input.operationId,'operationId');if(log.operations.some(op=>op.operationId===operationId))throw new Error('Duplicate migration operation id');const op:MigrationLogEntry=Object.freeze({sequence:log.operations.length+1,operationId,kind:input.kind,internalId:required(input.internalId,'internalId'),executedAt:instant(input.executedAt,'executedAt')});return Object.freeze({...log,operations:Object.freeze([...log.operations,op])});}
export function finishMigration(log:Readonly<MigrationLog>,status:'completed'|'failed',completedAt:string):Readonly<MigrationLog>{if(log.status!=='running')throw new Error('Migration is not running');return Object.freeze({...log,status,completedAt:instant(completedAt,'completedAt')});}
export function markMigrationRolledBack(log:Readonly<MigrationLog>,at:string):Readonly<MigrationLog>{if(log.status!=='completed'&&log.status!=='failed')throw new Error('Only finished migrations can be rolled back');return Object.freeze({...log,status:'rolled-back',completedAt:instant(at,'rolledBackAt')});}
export function createRollbackPlan(input:{tenantId:string;migrationId:string;steps:readonly {type:'delete'|'restore';internalId:string;restore?:RollbackPersonSnapshot}[]}):Readonly<RollbackPlan>{const steps=input.steps.map((step,index)=>{if(step.type==='restore'&&!step.restore)throw new Error('Restore step requires snapshot');if(step.type==='delete'&&step.restore)throw new Error('Delete step must not include snapshot');return Object.freeze({sequence:index+1,type:step.type,internalId:required(step.internalId,'internalId'),...(step.restore?{restore:cloneSnapshot(step.restore)}:{})});});return Object.freeze({tenantId:required(input.tenantId,'tenantId'),migrationId:required(input.migrationId,'migrationId'),steps:Object.freeze(steps)});}
