export const MIGRATION_SCHEMA_VERSION=1 as const;
export const MIGRATION_LIMITS=Object.freeze({maxRows:10000,maxExternalId:200,maxDisplayName:200,maxLocale:35,maxField:10000,maxCsvBytes:5_000_000,maxJsonBytes:5_000_000});
export interface MigrationPersonRow{readonly externalId:string;readonly displayName:string;readonly active:boolean;readonly preferredLocale?:string;readonly sourceRow?:number;readonly errors:readonly string[];readonly isValid:boolean}
export interface MigrationSchema{readonly version:typeof MIGRATION_SCHEMA_VERSION;readonly exportedAt:string;readonly rows:readonly MigrationPersonRow[]}
function instant(v:string):void{if(!Number.isFinite(Date.parse(v)))throw new Error('Invalid exportedAt');}
function locale(v:string):string|undefined{const n=v.trim();if(!n)return undefined;if(n.length>MIGRATION_LIMITS.maxLocale)throw new Error('preferredLocale is too long');try{return new Intl.Locale(n).toString();}catch{throw new Error('Invalid preferredLocale');}}
function exactKeys(o:Record<string,unknown>,allowed:readonly string[],label:string):void{const set=new Set(allowed);const bad=Object.keys(o).filter(k=>!set.has(k));if(bad.length)throw new Error(`${label} contains unknown fields: ${bad.sort().join(', ')}`);}
function requiredText(v:unknown,label:string,max:number):string{if(typeof v!=='string')throw new Error(`${label} must be a string`);const n=v.trim().replace(/\s+/g,' ');if(!n)throw new Error(`${label} is required`);if(n.length>max)throw new Error(`${label} is too long`);if(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(n))throw new Error(`${label} contains control characters`);return n;}
function booleanValue(v:unknown):boolean{if(typeof v==='boolean')return v;if(typeof v==='string'){const n=v.trim().toLowerCase();if(['true','1','yes','y','sim','sí'].includes(n))return true;if(['false','0','no','n','não'].includes(n))return false;}throw new Error('active must be a boolean');}
export function normalizeMigrationRow(input:unknown,sourceRow?:number):Readonly<MigrationPersonRow>{const errors:string[]=[];let externalId='';let displayName='';let active=false;let preferredLocale:string|undefined;if(!input||typeof input!=='object'||Array.isArray(input)){return Object.freeze({externalId,displayName,active,sourceRow,errors:Object.freeze(['row must be an object']),isValid:false});}const c=input as Record<string,unknown>;try{externalId=requiredText(c.externalId,'externalId',MIGRATION_LIMITS.maxExternalId);}catch(e){errors.push((e as Error).message);}try{displayName=requiredText(c.displayName,'displayName',MIGRATION_LIMITS.maxDisplayName);}catch(e){errors.push((e as Error).message);}try{active=booleanValue(c.active);}catch(e){errors.push((e as Error).message);}if(c.preferredLocale!==undefined&&c.preferredLocale!==null&&c.preferredLocale!==''){try{if(typeof c.preferredLocale!=='string')throw new Error('preferredLocale must be a string');preferredLocale=locale(c.preferredLocale);}catch(e){errors.push((e as Error).message);}}const row:MigrationPersonRow={externalId,displayName,active,...(preferredLocale?{preferredLocale}:{}),...(sourceRow!==undefined?{sourceRow}:{}),errors:Object.freeze(errors),isValid:errors.length===0};return Object.freeze(row);}
export function createMigrationSchema(rows:readonly unknown[],exportedAt:string):Readonly<MigrationSchema>{instant(exportedAt);if(rows.length>MIGRATION_LIMITS.maxRows)throw new Error('Too many migration rows');return Object.freeze({version:MIGRATION_SCHEMA_VERSION,exportedAt,rows:Object.freeze(rows.map((r,i)=>normalizeMigrationRow(r,i+1)))});}
export function validateMigrationSchema(value:unknown):Readonly<MigrationSchema>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Migration schema must be an object');const c=value as Record<string,unknown>;exactKeys(c,['version','exportedAt','rows'],'Migration schema');if(c.version!==MIGRATION_SCHEMA_VERSION)throw new Error('Unsupported migration schema version');if(typeof c.exportedAt!=='string')throw new Error('exportedAt must be a string');instant(c.exportedAt);if(!Array.isArray(c.rows))throw new Error('rows must be an array');if(c.rows.length>MIGRATION_LIMITS.maxRows)throw new Error('Too many migration rows');const rows=c.rows.map((raw,i)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error(`row ${i+1} must be an object`);const r=raw as Record<string,unknown>;exactKeys(r,['externalId','displayName','active','preferredLocale','sourceRow','errors','isValid'],`row ${i+1}`);return normalizeMigrationRow(r,typeof r.sourceRow==='number'?r.sourceRow:i+1);});return Object.freeze({version:MIGRATION_SCHEMA_VERSION,exportedAt:c.exportedAt,rows:Object.freeze(rows)});}
