import { MIGRATION_LIMITS, normalizeMigrationRow } from './migration-schema';
export const PORTABLE_FORMAT='eutaktos-portable' as const;
export const PORTABLE_VERSION=1 as const;
export interface PortablePerson{readonly externalId:string;readonly displayName:string;readonly active:boolean;readonly preferredLocale?:string}
export interface PortableDocument{readonly format:typeof PORTABLE_FORMAT;readonly version:typeof PORTABLE_VERSION;readonly exportedAt:string;readonly sourceTenantId:string;readonly people:readonly PortablePerson[]}
function exact(o:Record<string,unknown>,allowed:readonly string[],label:string):void{const set=new Set(allowed);const bad=Object.keys(o).filter(k=>!set.has(k));if(bad.length)throw new Error(`${label} contains unknown fields: ${bad.sort().join(', ')}`);}
function instant(v:string):void{if(!Number.isFinite(Date.parse(v)))throw new Error('Invalid exportedAt');}
function required(v:unknown,label:string,max=200):string{if(typeof v!=='string')throw new Error(`${label} must be a string`);const n=v.trim();if(!n)throw new Error(`${label} is required`);if(n.length>max)throw new Error(`${label} is too long`);return n;}
function person(value:unknown,index:number):PortablePerson{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`people[${index}] must be an object`);const c=value as Record<string,unknown>;exact(c,['externalId','displayName','active','preferredLocale'],`people[${index}]`);const normalized=normalizeMigrationRow(c,index+1);if(!normalized.isValid)throw new Error(`Invalid person at index ${index}: ${normalized.errors.join('; ')}`);return Object.freeze({externalId:normalized.externalId,displayName:normalized.displayName,active:normalized.active,...(normalized.preferredLocale?{preferredLocale:normalized.preferredLocale}:{})});}
function validate(doc:unknown):Readonly<PortableDocument>{if(!doc||typeof doc!=='object'||Array.isArray(doc))throw new Error('Portable document must be an object');const c=doc as Record<string,unknown>;exact(c,['format','version','exportedAt','sourceTenantId','people'],'Portable document');if(c.format!==PORTABLE_FORMAT)throw new Error('Invalid portable format');if(c.version!==PORTABLE_VERSION)throw new Error('Unsupported portable version');if(typeof c.exportedAt!=='string')throw new Error('exportedAt must be a string');instant(c.exportedAt);const sourceTenantId=required(c.sourceTenantId,'sourceTenantId');if(!Array.isArray(c.people))throw new Error('people must be an array');if(c.people.length>MIGRATION_LIMITS.maxRows)throw new Error('Too many people');const people=c.people.map(person);const seen=new Set<string>();for(const p of people){if(seen.has(p.externalId))throw new Error(`Duplicate externalId: ${p.externalId}`);seen.add(p.externalId);}return Object.freeze({format:PORTABLE_FORMAT,version:PORTABLE_VERSION,exportedAt:c.exportedAt,sourceTenantId,people:Object.freeze(people)});}
export function serializePortableJson(input:{sourceTenantId:string;people:readonly PortablePerson[]},exportedAt:string):string{return `${JSON.stringify(validate({format:PORTABLE_FORMAT,version:PORTABLE_VERSION,exportedAt,sourceTenantId:input.sourceTenantId,people:input.people}),null,2)}\n`;}
export function parsePortableJson(text:string):Readonly<PortableDocument>{if(new TextEncoder().encode(text).length>MIGRATION_LIMITS.maxJsonBytes)throw new Error('Portable JSON is too large');let raw:unknown;try{raw=JSON.parse(text);}catch{throw new Error('Invalid portable JSON');}return validate(raw);}
